### PR TITLE
Initial User Portal Page

### PR DESCRIPTION
**Pull request by nazifatanzim**
https://github.com/NicolasDuciaume/SYSC4806_Web_App/issues/36
- converted "compare_talent" to user portal

### CODE REVIEW

**Review by Calacorm — CHANGES_REQUESTED** [review]
Looks good, Can you confirm that the upgrade and delete account buttons are placeholders for now? That is, not hooked up to control?

**Review by NicolasDuciaume — APPROVED** [review]
Although Role isn't taken into account to verify that the user is in fact a user and not an admin, the code looks good and shouldn't have any issue merging with my login/registration update branch

**Comment by nazifatanzim** [comment]
> Looks good, Can you confirm that the upgrade and delete account buttons are placeholders for now? That is, not hooked up to control?

Yes they are. They will later redirect to the appropriate pages once they are implemented

**Comment by nazifatanzim** [comment]
> Although Role isn't taken into account to verify that the user is in fact a user and not an admin, the code looks good and shouldn't have any issue merging with my login/registration update branch

Role will be taken into account with the next user portal sub-feature.

**Review by Calacorm — APPROVED** [review]
- I understand added tests will be fleshed out on another feature branch

**Pull request merged**
